###############################################################################
## Copyright (C) 2024 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################
#adrv904x

set_property -dict {PACKAGE_PIN M15} [get_ports ref_clk0_p]
set_property -dict {PACKAGE_PIN M14} [get_ports ref_clk0_n]
set_property -dict {PACKAGE_PIN K15} [get_ports ref_clk1_p]
set_property -dict {PACKAGE_PIN K14} [get_ports ref_clk1_n]

set_property IOSTANDARD LVDS15 [get_ports core_clk_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports core_clk_p]
set_property PACKAGE_PIN AV23 [get_ports core_clk_p]
set_property PACKAGE_PIN AW23 [get_ports core_clk_n]
set_property IOSTANDARD LVDS15 [get_ports core_clk_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports core_clk_n]

set_property -dict {PACKAGE_PIN AB2} [get_ports {rx_data_p[0]}]
set_property -dict {PACKAGE_PIN AB1} [get_ports {rx_data_n[0]}]
set_property -dict {PACKAGE_PIN AA4} [get_ports {rx_data_p[1]}]
set_property -dict {PACKAGE_PIN AA3} [get_ports {rx_data_n[1]}]
set_property -dict {PACKAGE_PIN Y2} [get_ports {rx_data_p[2]}]
set_property -dict {PACKAGE_PIN Y1} [get_ports {rx_data_n[2]}]
set_property -dict {PACKAGE_PIN W4} [get_ports {rx_data_p[3]}]
set_property -dict {PACKAGE_PIN W3} [get_ports {rx_data_n[3]}]
set_property -dict {PACKAGE_PIN V2} [get_ports {rx_data_p[4]}]
set_property -dict {PACKAGE_PIN V1} [get_ports {rx_data_n[4]}]
set_property -dict {PACKAGE_PIN U4} [get_ports {rx_data_p[5]}]
set_property -dict {PACKAGE_PIN U3} [get_ports {rx_data_n[5]}]
set_property -dict {PACKAGE_PIN T2} [get_ports {rx_data_p[6]}]
set_property -dict {PACKAGE_PIN T1} [get_ports {rx_data_n[6]}]
set_property -dict {PACKAGE_PIN R4} [get_ports {rx_data_p[7]}]
set_property -dict {PACKAGE_PIN R3} [get_ports {rx_data_n[7]}]

set_property -dict {PACKAGE_PIN AB7} [get_ports {tx_data_p[0]}]
set_property -dict {PACKAGE_PIN AB6} [get_ports {tx_data_n[0]}]
set_property -dict {PACKAGE_PIN AA9} [get_ports {tx_data_p[1]}]
set_property -dict {PACKAGE_PIN AA8} [get_ports {tx_data_n[1]}]
set_property -dict {PACKAGE_PIN Y7} [get_ports {tx_data_p[2]}]
set_property -dict {PACKAGE_PIN Y6} [get_ports {tx_data_n[2]}]
set_property -dict {PACKAGE_PIN W9} [get_ports {tx_data_p[3]}]
set_property -dict {PACKAGE_PIN W8} [get_ports {tx_data_n[3]}]
set_property -dict {PACKAGE_PIN V7} [get_ports {tx_data_p[4]}]
set_property -dict {PACKAGE_PIN V6} [get_ports {tx_data_n[4]}]
set_property -dict {PACKAGE_PIN U9} [get_ports {tx_data_p[5]}]
set_property -dict {PACKAGE_PIN U8} [get_ports {tx_data_n[5]}]
set_property -dict {PACKAGE_PIN T7} [get_ports {tx_data_p[6]}]
set_property -dict {PACKAGE_PIN T6} [get_ports {tx_data_n[6]}]
set_property -dict {PACKAGE_PIN R9} [get_ports {tx_data_p[7]}]
set_property -dict {PACKAGE_PIN R8} [get_ports {tx_data_n[7]}]

set_property -dict {PACKAGE_PIN AW24 IOSTANDARD LVDS15} [get_ports rx_sync_p]
set_property -dict {PACKAGE_PIN AY25 IOSTANDARD LVDS15} [get_ports rx_sync_n]
set_property -dict {PACKAGE_PIN AN20 IOSTANDARD LVDS15} [get_ports rx_sync_1_p]
set_property -dict {PACKAGE_PIN AN19 IOSTANDARD LVDS15} [get_ports rx_sync_1_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_p]
set_property PACKAGE_PIN AR18 [get_ports tx_sync_p]
set_property PACKAGE_PIN AT19 [get_ports tx_sync_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_1_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_1_p]
set_property PACKAGE_PIN BF16 [get_ports tx_sync_1_p]
set_property PACKAGE_PIN BG16 [get_ports tx_sync_1_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_1_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_1_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_2_p]
set_property PACKAGE_PIN AU20 [get_ports tx_sync_2_p]
set_property PACKAGE_PIN AU19 [get_ports tx_sync_2_n]
set_property IOSTANDARD LVDS15 [get_ports tx_sync_2_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports tx_sync_2_n]

set_property IOSTANDARD LVDS15 [get_ports sysref_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_p]
set_property PACKAGE_PIN BC23 [get_ports sysref_p]
set_property PACKAGE_PIN BD22 [get_ports sysref_n]
set_property IOSTANDARD LVDS15 [get_ports sysref_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref_n]
set_property -dict {PACKAGE_PIN AV22 IOSTANDARD LVDS15} [get_ports sysref_out_p]
set_property -dict {PACKAGE_PIN AW21 IOSTANDARD LVDS15} [get_ports sysref_out_n]

set_property -dict {PACKAGE_PIN BG19 IOSTANDARD LVCMOS15} [get_ports ad9528_sysref_req]
set_property -dict {PACKAGE_PIN BF24 IOSTANDARD LVCMOS15} [get_ports adrv904x_test]

set_property -dict {PACKAGE_PIN BC20 IOSTANDARD LVCMOS15} [get_ports adrv904x_orx0_enable]
set_property -dict {PACKAGE_PIN BD20 IOSTANDARD LVCMOS15} [get_ports adrv904x_orx1_enable]
set_property -dict {PACKAGE_PIN BE21 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx0_enable]
set_property -dict {PACKAGE_PIN BE20 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx1_enable]
set_property -dict {PACKAGE_PIN BG25 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx2_enable]
set_property -dict {PACKAGE_PIN BG24 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx3_enable]
set_property -dict {PACKAGE_PIN BB20 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx4_enable]
set_property -dict {PACKAGE_PIN BB19 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx5_enable]
set_property -dict {PACKAGE_PIN AU24 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx6_enable]
set_property -dict {PACKAGE_PIN AU23 IOSTANDARD LVCMOS15} [get_ports adrv904x_trx7_enable]

set_property -dict {PACKAGE_PIN AY22 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[0]}]
set_property -dict {PACKAGE_PIN AY23 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[1]}]
set_property -dict {PACKAGE_PIN BF21 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[2]}]
set_property -dict {PACKAGE_PIN BG20 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[3]}]
set_property -dict {PACKAGE_PIN BE19 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[4]}]
set_property -dict {PACKAGE_PIN BD19 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[5]}]
set_property -dict {PACKAGE_PIN BE17 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[6]}]
set_property -dict {PACKAGE_PIN BD17 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[7]}]
set_property -dict {PACKAGE_PIN BA17 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[8]}]
set_property -dict {PACKAGE_PIN BA16 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[9]}]
set_property -dict {PACKAGE_PIN BF18 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[10]}]
set_property -dict {PACKAGE_PIN BG18 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[11]}]
set_property -dict {PACKAGE_PIN AU21 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[12]}]
set_property -dict {PACKAGE_PIN AV21 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[13]}]
set_property -dict {PACKAGE_PIN AM21 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[14]}]
set_property -dict {PACKAGE_PIN AM20 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[15]}]
set_property -dict {PACKAGE_PIN BG21 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[16]}]
set_property -dict {PACKAGE_PIN BF22 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[17]}]
set_property -dict {PACKAGE_PIN BG23 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[18]}]
set_property -dict {PACKAGE_PIN BE16 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[19]}]
set_property -dict {PACKAGE_PIN AT20 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[20]}]
set_property -dict {PACKAGE_PIN AR20 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[21]}]
set_property -dict {PACKAGE_PIN BA20 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[22]}]
set_property -dict {PACKAGE_PIN BA19 IOSTANDARD LVCMOS15} [get_ports {adrv904x_gpio[23]}]

set_property -dict {PACKAGE_PIN BF19 IOSTANDARD LVCMOS15} [get_ports ad9528_reset_b]
set_property -dict {PACKAGE_PIN BF17 IOSTANDARD LVCMOS15} [get_ports adrv904x_reset_b]

set_property -dict {PACKAGE_PIN BE25 IOSTANDARD LVCMOS15} [get_ports spi_csn_adrv904x]
set_property -dict {PACKAGE_PIN BE24 IOSTANDARD LVCMOS15} [get_ports spi_csn_ad9528]
set_property -dict {PACKAGE_PIN BC25 IOSTANDARD LVCMOS15} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN BC22 IOSTANDARD LVCMOS15} [get_ports spi_miso]
set_property -dict {PACKAGE_PIN BD25 IOSTANDARD LVCMOS15} [get_ports spi_mosi]

# clocks

create_clock -period 4.069  -name device_clk [get_ports core_clk_p]
create_clock -period 4.069  -name ref_clk [get_ports ref_clk0_p]
# create_clock -period 4.069  -name link_clk [get_ports ref_clk1_p]


